package com.aikundli.util

import android.content.Context
import android.content.Intent
import android.graphics.*
import android.graphics.pdf.PdfDocument
import android.os.Environment
import androidx.core.content.FileProvider
import com.aikundli.model.HoroscopeResult
import com.aikundli.model.KundliResponse
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

object PdfGenerator {

    fun generateAndShare(
        context  : Context,
        kundli   : KundliResponse,
        horoscope: HoroscopeResult?
    ) {
        try {
            val pdf    = PdfDocument()
            val page   = pdf.startPage(PdfDocument.PageInfo.Builder(595, 842, 1).create())
            val canvas = page.canvas
            drawPdfContent(canvas, kundli, horoscope)
            pdf.finishPage(page)

            val fileName = "Kundli_${SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())}.pdf"
            val dir  = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS)
                ?: context.filesDir
            val file = File(dir, fileName)
            pdf.writeTo(FileOutputStream(file))
            pdf.close()

            sharePdf(context, file)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    private fun drawPdfContent(
        canvas   : Canvas,
        kundli   : KundliResponse,
        horoscope: HoroscopeResult?
    ) {
        val titlePaint = Paint().apply {
            color       = Color.parseColor("#6A0572")
            textSize    = 28f
            typeface    = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }
        val headingPaint = Paint().apply {
            color       = Color.parseColor("#1565C0")
            textSize    = 18f
            typeface    = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }
        val bodyPaint = Paint().apply {
            color       = Color.BLACK
            textSize    = 13f
            isAntiAlias = true
        }
        val linePaint = Paint().apply {
            color       = Color.parseColor("#6A0572")
            strokeWidth = 1f
        }

        var y = 60f

        // Title
        canvas.drawText("AI Kundli Generator Report", 40f, y, titlePaint); y += 40f
        canvas.drawLine(40f, y, 555f, y, linePaint);                       y += 20f

        // Summary
        canvas.drawText("Birth Chart Summary", 40f, y, headingPaint); y += 25f
        canvas.drawText("Ascendant : ${kundli.ascendant}", 40f, y, bodyPaint); y += 20f
        canvas.drawText("Sun Sign  : ${kundli.sunSign}",   40f, y, bodyPaint); y += 20f
        canvas.drawText("Moon Sign : ${kundli.moonSign}",  40f, y, bodyPaint); y += 20f
        if (kundli.nakshatra.isNotBlank()) {
            canvas.drawText("Nakshatra : ${kundli.nakshatra}", 40f, y, bodyPaint); y += 20f
        }
        y += 10f

        // Planets
        canvas.drawText("Planetary Positions", 40f, y, headingPaint); y += 25f
        kundli.planets.forEach { planet ->
            if (y > 780f) return@forEach
            canvas.drawText(
                "  ${planet.planet.padEnd(10)} ${planet.sign.padEnd(14)} House ${planet.house}${if (planet.isRetro) " (R)" else ""}",
                40f, y, bodyPaint
            )
            y += 18f
        }
        y += 10f
        canvas.drawLine(40f, y, 555f, y, linePaint); y += 20f

        // Horoscope
        horoscope?.let { h ->
            canvas.drawText("AI Horoscope Interpretation", 40f, y, headingPaint); y += 25f
            listOf(
                "Personality"   to h.personality,
                "Career"        to h.career,
                "Relationships" to h.marriage,
                "Finance"       to h.finance,
                "Health"        to h.health,
                "Lucky Numbers" to h.luckyNumbers,
                "Lucky Colors"  to h.luckyColors,
            ).forEach { (section, text) ->
                if (text.isBlank() || y > 780f) return@forEach
                canvas.drawText("$section:", 40f, y, headingPaint.apply { textSize = 14f }); y += 18f
                // Simple word-wrap
                val words = text.split(" ")
                var line  = ""
                words.forEach { word ->
                    val candidate = if (line.isEmpty()) word else "$line $word"
                    if (bodyPaint.measureText(candidate) < 510f) {
                        line = candidate
                    } else {
                        if (y < 780f) canvas.drawText(line, 48f, y, bodyPaint)
                        y += 16f; line = word
                    }
                }
                if (line.isNotEmpty() && y < 780f) canvas.drawText(line, 48f, y, bodyPaint)
                y += 20f
            }
        }

        // Footer
        canvas.drawText(
            "Generated by AI Kundli Generator  •  ${SimpleDateFormat("dd MMM yyyy", Locale.US).format(Date())}",
            40f, 820f, bodyPaint.apply { color = Color.GRAY; textSize = 10f }
        )
    }

    private fun sharePdf(context: Context, file: File) {
        val uri = FileProvider.getUriForFile(
            context, "${context.packageName}.fileprovider", file
        )
        val intent = Intent(Intent.ACTION_SEND).apply {
            type  = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Share Kundli PDF"))
    }
}
